wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/acanthaster_planci_gca001949145v1/pep/Acanthaster_planci_gca001949145v1.OKI_Apl_1.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/acropora_millepora_gca013753865v1/pep/Acropora_millepora_gca013753865v1.Amil_v2.1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/actinia_equina_gca011057435/pep/Actinia_equina_gca011057435.equina_smartden.arrow4.noredun.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/actinia_tenebrosa_gca009602425v1/pep/Actinia_tenebrosa_gca009602425v1.GCA009602425v1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/acyrthosiphon_pisum/pep/Acyrthosiphon_pisum.pea_aphid_22Mar2018_4r6ur.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/adineta_vaga/pep/Adineta_vaga.AMS_PRJEB1171_v1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/aedes_aegypti_lvpagwg/pep/Aedes_aegypti_lvpagwg.AaegL5.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/aedes_albopictus/pep/Aedes_albopictus.AaloF1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/agrilus_planipennis_gca000699045v2/pep/Agrilus_planipennis_gca000699045v2.Apla_2.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/amphibalanus_amphitrite_gca019059575v1/pep/Amphibalanus_amphitrite_gca019059575v1.NRLGWU_Aamphi_draft.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/amphimedon_queenslandica/pep/Amphimedon_queenslandica.Aqu1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/anneissia_japonica_gca011630105v1/pep/Anneissia_japonica_gca011630105v1.GCA011630105v1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/anopheles_albimanus/pep/Anopheles_albimanus.AalbS2.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/anopheles_arabiensis/pep/Anopheles_arabiensis.AaraD1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/anopheles_atroparvus/pep/Anopheles_atroparvus.AatrE3.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/anopheles_atroparvus_gca914969975/pep/Anopheles_atroparvus_gca914969975.atroparvus_hifiasm_n225_277Mb.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/anopheles_christyi/pep/Anopheles_christyi.AchrA1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/anopheles_coluzzii/pep/Anopheles_coluzzii.AcolM1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/anopheles_coluzzii_ngousso/pep/Anopheles_coluzzii_ngousso.AcolN1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/anopheles_culicifacies/pep/Anopheles_culicifacies.AculA1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/anopheles_darlingi/pep/Anopheles_darlingi.AdarC3.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/anopheles_dirus/pep/Anopheles_dirus.AdirW1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/anopheles_epiroticus/pep/Anopheles_epiroticus.AepiE1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/anopheles_farauti/pep/Anopheles_farauti.AfarF2.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/anopheles_funestus/pep/Anopheles_funestus.AfunF3.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/anopheles_gambiae/pep/Anopheles_gambiae.AgamP4.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/anopheles_maculatus/pep/Anopheles_maculatus.AmacM1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/anopheles_melas/pep/Anopheles_melas.AmelC2.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/anopheles_merus/pep/Anopheles_merus.AmerM2.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/anopheles_minimus/pep/Anopheles_minimus.AminM1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/anopheles_quadriannulatus/pep/Anopheles_quadriannulatus.AquaS1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/anopheles_sinensis/pep/Anopheles_sinensis.AsinS2.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/anopheles_sinensis_china/pep/Anopheles_sinensis_china.AsinC2.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/anopheles_stephensi/pep/Anopheles_stephensi.AsteS1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/anopheles_stephensi_indian/pep/Anopheles_stephensi_indian.AsteI2.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/anoplophora_glabripennis/pep/Anoplophora_glabripennis.Agla_2.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/aphidius_gifuensis_gca014905175v1/pep/Aphidius_gifuensis_gca014905175v1.GCA014905175v1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/apis_mellifera/pep/Apis_mellifera.Amel_HAv3.1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/aplysia_californica_gca000002075v2/pep/Aplysia_californica_gca000002075v2.AplCal3.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/ascaris_suum/pep/Ascaris_suum.ASM18702v3.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/asterias_rubens_gca902459465v3/pep/Asterias_rubens_gca902459465v3.eAstRub1.3.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/athalia_rosae_gca000344095v2/pep/Athalia_rosae_gca000344095v2.Aros_2.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/atta_cephalotes/pep/Atta_cephalotes.Attacep1.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/bactrocera_dorsalis_gca000789215v2/pep/Bactrocera_dorsalis_gca000789215v2.GCA000789215v2.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/bactrocera_latifrons_gca001853355v1/pep/Bactrocera_latifrons_gca001853355v1.GCA001853355v1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/bactrocera_tryoni_gca016617805v2/pep/Bactrocera_tryoni_gca016617805v2.CSIRO_BtryS06_freeze1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/belgica_antarctica/pep/Belgica_antarctica.ASM77530v1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/bemisia_tabaci_asiaii5/pep/Bemisia_tabaci_asiaii5.ASIAII5_n227_616Mb.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/bemisia_tabaci_ssa1nig/pep/Bemisia_tabaci_ssa1nig.SSA1SG1_Nigeria_n4493_656Mb.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/bemisia_tabaci_ssa1ug/pep/Bemisia_tabaci_ssa1ug.SSA1_SG1_Uganda_n955_657Mb.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/bemisia_tabaci_ssa2nig/pep/Bemisia_tabaci_ssa2nig.SSA2_Nigeria_n785_625mb.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/bemisia_tabaci_ssa3nig/pep/Bemisia_tabaci_ssa3nig.SSA3_Nigeria_2278n_648mb.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/bemisia_tabaci_uganda1/pep/Bemisia_tabaci_uganda1.Uganda1_n5713_630Mb.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/biomphalaria_glabrata/pep/Biomphalaria_glabrata.BglaB1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/bombus_impatiens/pep/Bombus_impatiens.BIMP_2.2.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/bombus_terrestris/pep/Bombus_terrestris.Bter_1.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/bombyx_mori/pep/Bombyx_mori.Bmori_2016v1.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/branchiostoma_lanceolatum/pep/Branchiostoma_lanceolatum.BraLan2.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/brugia_malayi/pep/Brugia_malayi.Bmal-4.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/caenorhabditis_brenneri/pep/Caenorhabditis_brenneri.C_brenneri-6.0.1b.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/caenorhabditis_briggsae/pep/Caenorhabditis_briggsae.CB4.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/caenorhabditis_elegans/pep/Caenorhabditis_elegans.WBcel235.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/caenorhabditis_japonica/pep/Caenorhabditis_japonica.C_japonica-7.0.1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/caenorhabditis_remanei/pep/Caenorhabditis_remanei.C_remanei-15.0.1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/capitella_teleta/pep/Capitella_teleta.Capitella_teleta_v1.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/centruroides_sculpturatus_gca000671375v2/pep/Centruroides_sculpturatus_gca000671375v2.Cexi_2.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/ceratitis_capitata_gca000347755v4/pep/Ceratitis_capitata_gca000347755v4.Ccap_2.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/cimex_lectularius/pep/Cimex_lectularius.Clec_2.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/clytia_hemisphaerica_gca902728285/pep/Clytia_hemisphaerica_gca902728285.GCA902728285v1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/copidosoma_floridanum_gca000648655v2/pep/Copidosoma_floridanum_gca000648655v2.Cflo_2.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/cotesia_glomerata_gca020080835v1/pep/Cotesia_glomerata_gca020080835v1.MPM_Cglom_v2.3.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/crassostrea_gigas/pep/Crassostrea_gigas.GCA902806645v1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/crassostrea_virginica_gca002022765v4/pep/Crassostrea_virginica_gca002022765v4.C_virginica_3.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/culex_quinquefasciatus/pep/Culex_quinquefasciatus.CpipJ2.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/culex_quinquefasciatus_gca015732765v1/pep/Culex_quinquefasciatus_gca015732765v1.VPISU_Cqui_1.0_pri_paternal.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/culicoides_sonorensis/pep/Culicoides_sonorensis.Cson1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/danaus_plexippus/pep/Danaus_plexippus.Dplex_v4.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/daphnia_magna/pep/Daphnia_magna.daphmag2.4.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/daphnia_magna_gca020631705v2/pep/Daphnia_magna_gca020631705v2.GCA020631705v2.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/daphnia_pulex/pep/Daphnia_pulex.V1.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/dendroctonus_ponderosae_gca000355655v1/pep/Dendroctonus_ponderosae_gca000355655v1.DendPond_male_gca000355655v1.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/dendronephthya_gigantea_gca004324835v1/pep/Dendronephthya_gigantea_gca004324835v1.DenGig_1.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/dermacentor_silvarum_gca013339745v1/pep/Dermacentor_silvarum_gca013339745v1.GCA013339745v1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/dermatophagoides_pteronyssinus_gca001901225v2/pep/Dermatophagoides_pteronyssinus_gca001901225v2.GCA001901225v2.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/diabrotica_virgifera_gca003013835v2/pep/Diabrotica_virgifera_gca003013835v2.Dvir_v2.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/dimorphilus_gyrociliatus_gca904063045v1/pep/Dimorphilus_gyrociliatus_gca904063045v1.GCA904063045v1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/dinothrombium_tinctorium/pep/Dinothrombium_tinctorium.DtinU1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/diuraphis_noxia_gca001186385v1/pep/Diuraphis_noxia_gca001186385v1.Dnoxia_1.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/drosophila_ananassae/pep/Drosophila_ananassae.dana_caf1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/drosophila_erecta/pep/Drosophila_erecta.dere_caf1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/drosophila_grimshawi/pep/Drosophila_grimshawi.dgri_caf1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/drosophila_melanogaster/pep/Drosophila_melanogaster.BDGP6.32.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/drosophila_mojavensis/pep/Drosophila_mojavensis.dmoj_caf1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/drosophila_persimilis/pep/Drosophila_persimilis.dper_caf1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/drosophila_pseudoobscura/pep/Drosophila_pseudoobscura.Dpse_3.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/drosophila_sechellia/pep/Drosophila_sechellia.dsec_caf1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/drosophila_simulans/pep/Drosophila_simulans.ASM75419v3.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/drosophila_virilis/pep/Drosophila_virilis.dvir_caf1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/drosophila_willistoni/pep/Drosophila_willistoni.dwil_caf1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/drosophila_yakuba/pep/Drosophila_yakuba.dyak_caf1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/eurytemora_affinis_gca000591075v2/pep/Eurytemora_affinis_gca000591075v2.Eaff_2.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/exaiptasia_diaphana_gca001417965v1/pep/Exaiptasia_diaphana_gca001417965v1.Aiptasia_genome_1.1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/folsomia_candida/pep/Folsomia_candida.ASM221717v1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/gigantopelta_aegis_gca016097555v1/pep/Gigantopelta_aegis_gca016097555v1.Gae_host_genome.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/glossina_austeni/pep/Glossina_austeni.GausT1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/glossina_brevipalpis/pep/Glossina_brevipalpis.GbreI1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/glossina_fuscipes/pep/Glossina_fuscipes.Yale_Gfus_2.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/glossina_morsitans/pep/Glossina_morsitans.GmorY1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/glossina_pallidipes/pep/Glossina_pallidipes.GpalI1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/glossina_palpalis/pep/Glossina_palpalis.GpapI1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/haemaphysalis_longicornis_gca013339765v1/pep/Haemaphysalis_longicornis_gca013339765v1.GCA013339765v1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/heliconius_melpomene/pep/Heliconius_melpomene.Hmel1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/helobdella_robusta/pep/Helobdella_robusta.Helro1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/hermetia_illucens_gca905115235v1/pep/Hermetia_illucens_gca905115235v1.GCA905115235v1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/hofstenia_miamia/pep/Hofstenia_miamia.HmiaM1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/homarus_americanus_gca018991925v1/pep/Homarus_americanus_gca018991925v1.GMGI_Hamer_2.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/hyalella_azteca_gca000764305v2/pep/Hyalella_azteca_gca000764305v2.Hazt_2.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/hyalomma_asiaticum_gca013339685v1/pep/Hyalomma_asiaticum_gca013339685v1.GCA013339685v1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/hydra_vulgaris_gca000004095v1/pep/Hydra_vulgaris_gca000004095v1.GCA000004095v1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/hymenolepis_microstoma/pep/Hymenolepis_microstoma.HMN_v3.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/hypsibius_exemplaris_gca002082055v1/pep/Hypsibius_exemplaris_gca002082055v1.nHd_3.1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/ixodes_persulcatus_gca013358835v1/pep/Ixodes_persulcatus_gca013358835v1.BIME_Iper_1.3.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/ixodes_scapularis/pep/Ixodes_scapularis.IscaW1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/ixodes_scapularis_gca016920785v2/pep/Ixodes_scapularis_gca016920785v2.GCA016920785v2.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/ixodes_scapularis_ise6/pep/Ixodes_scapularis_ise6.IscaI1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/lepeophtheirus_salmonis/pep/Lepeophtheirus_salmonis.LSalAtl2s.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/leptinotarsa_decemlineata_gca000500325v2/pep/Leptinotarsa_decemlineata_gca000500325v2.Ldec_2.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/leptotrombidium_deliense/pep/Leptotrombidium_deliense.LdelU1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/limulus_polyphemus_gca000517525v1/pep/Limulus_polyphemus_gca000517525v1.Limulus_polyphemus_2.1.2.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/lingula_anatina/pep/Lingula_anatina.LinAna1.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/lingula_anatina_gca001039355v2/pep/Lingula_anatina_gca001039355v2.LinAna2.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/loa_loa/pep/Loa_loa.Loa_loa_V3.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/lottia_gigantea/pep/Lottia_gigantea.Lotgi1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/lucilia_cuprina/pep/Lucilia_cuprina.ASM118794v1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/lutzomyia_longipalpis/pep/Lutzomyia_longipalpis.LlonJ1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/lytechinus_variegatus_gca018143015v1/pep/Lytechinus_variegatus_gca018143015v1.Lvar_3.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/mayetiola_destructor/pep/Mayetiola_destructor.Mdes_1.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/megaselia_scalaris/pep/Megaselia_scalaris.Msca1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/melitaea_cinxia/pep/Melitaea_cinxia.MelCinx1.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/mercenaria_mercenaria_gca014805675v2/pep/Mercenaria_mercenaria_gca014805675v2.ASM1480567v1.1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/metaseiulus_occidentalis_gca000255335v1/pep/Metaseiulus_occidentalis_gca000255335v1.Mocc_1.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/mizuhopecten_yessoensis_gca002113885v2/pep/Mizuhopecten_yessoensis_gca002113885v2.GCA002113885v2.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/mnemiopsis_leidyi/pep/Mnemiopsis_leidyi.MneLei_Aug2011.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/monomorium_pharaonis_gca013373865v2/pep/Monomorium_pharaonis_gca013373865v2.GCA013373865v2.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/musca_domestica/pep/Musca_domestica.MdomA1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/nasonia_vitripennis/pep/Nasonia_vitripennis.Nvit_psr_1.1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/necator_americanus/pep/Necator_americanus.N_americanus_v1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/nematostella_vectensis/pep/Nematostella_vectensis.ASM20922v1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/octopus_bimaculoides/pep/Octopus_bimaculoides.PRJNA270931.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/octopus_bimaculoides_gca001194135v1/pep/Octopus_bimaculoides_gca001194135v1.Octopus_bimaculoides_v2_0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/octopus_sinensis_gca006345805v1/pep/Octopus_sinensis_gca006345805v1.GCA006345805v1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/onchocerca_volvulus/pep/Onchocerca_volvulus.ASM49940v2.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/onthophagus_taurus_gca000648695v2/pep/Onthophagus_taurus_gca000648695v2.Otau_2.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/ooceraea_biroi_gca003672135v1/pep/Ooceraea_biroi_gca003672135v1.Obir_v5.4.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/orbicella_faveolata_gca002042975v1/pep/Orbicella_faveolata_gca002042975v1.ofav_dov_v1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/orchesella_cincta/pep/Orchesella_cincta.ASM171814v1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/orussus_abietinus_gca000612105v2/pep/Orussus_abietinus_gca000612105v2.Oabi_2.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/owenia_fusiformis_gca903813345v1/pep/Owenia_fusiformis_gca903813345v1.GCA903813345v1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/parasteatoda_tepidariorum_gca000365465v3/pep/Parasteatoda_tepidariorum_gca000365465v3.Ptep_3.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/patiria_miniata_gca015706575v1/pep/Patiria_miniata_gca015706575v1.GCA015706575v1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/pediculus_humanus/pep/Pediculus_humanus.PhumU2.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/penaeus_japonicus_gca017312705v1/pep/Penaeus_japonicus_gca017312705v1.Mj_TUMSAT_v1.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/penaeus_monodon_gca015228065v1/pep/Penaeus_monodon_gca015228065v1.NSTDA_Pmon_1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/penaeus_vannamei_gca003789085v1/pep/Penaeus_vannamei_gca003789085v1.GCA003789085v1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/phlebotomus_papatasi/pep/Phlebotomus_papatasi.PpapI1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/phlebotomus_perniciosus_gca918844115/pep/Phlebotomus_perniciosus_gca918844115.pperniciosus_illum_n82538_165Mb.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/pocillopora_damicornis_gca003704095v1/pep/Pocillopora_damicornis_gca003704095v1.GCA003704095v1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/pollicipes_pollicipes_gca011947565v2/pep/Pollicipes_pollicipes_gca011947565v2.Ppol_2.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/pomacea_canaliculata_gca003073045v1/pep/Pomacea_canaliculata_gca003073045v1.GCA003073045v1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/portunus_trituberculatus_gca017591435v1/pep/Portunus_trituberculatus_gca017591435v1.GCA017591435v1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/priapulus_caudatus_gca000485595v2/pep/Priapulus_caudatus_gca000485595v2.Priapulus_caudatus-5.0.1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/pristionchus_pacificus/pep/Pristionchus_pacificus.El_Paco_fix.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/procambarus_clarkii_gca020424385v2/pep/Procambarus_clarkii_gca020424385v2.GCA020424385v2.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/rhagoletis_pomonella_gca013731165v1/pep/Rhagoletis_pomonella_gca013731165v1.Rhpom_1.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/rhipicephalus_microplus_gca013339725v1/pep/Rhipicephalus_microplus_gca013339725v1.GCA013339725v1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/rhipicephalus_sanguineus_gca013339695v1/pep/Rhipicephalus_sanguineus_gca013339695v1.GCA013339695v1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/rhodnius_prolixus/pep/Rhodnius_prolixus.RproC3.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/rhopalosiphum_maidis_gca003676215v3/pep/Rhopalosiphum_maidis_gca003676215v3.GCA003676215v3.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/saccoglossus_kowalevskii_gca000003605v1/pep/Saccoglossus_kowalevskii_gca000003605v1.GCA000003605v1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/sarcoptes_scabiei/pep/Sarcoptes_scabiei.GCA014595675v1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/schistosoma_mansoni/pep/Schistosoma_mansoni.Smansoni_v7.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/sipha_flava_gca003268045v1/pep/Sipha_flava_gca003268045v1.YSA_version1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/solenopsis_invicta/pep/Solenopsis_invicta.UNIL_Sinv_3.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/stegodyphus_mimosarum/pep/Stegodyphus_mimosarum.Stegodyphus_mimosarum_v1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/stomoxys_calcitrans/pep/Stomoxys_calcitrans.ScalU1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/strigamia_maritima/pep/Strigamia_maritima.Smar1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/strongylocentrotus_purpuratus/pep/Strongylocentrotus_purpuratus.Spur_5.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/strongyloides_ratti/pep/Strongyloides_ratti.S_ratti_ED321_v5_0_4.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/stylophora_pistillata_gca002571385v1/pep/Stylophora_pistillata_gca002571385v1.Stylophora_pistillata_v1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/teleopsis_dalmanni/pep/Teleopsis_dalmanni.GCA002237135v2.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/tetranychus_urticae/pep/Tetranychus_urticae.ASM23943v1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/thelohanellus_kitauei/pep/Thelohanellus_kitauei.ASM82789v1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/tigriopus_californicus_gca007210705/pep/Tigriopus_californicus_gca007210705.Tcal_SD_v2.1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/trialeurodes_vaporariorum_gca011764245/pep/Trialeurodes_vaporariorum_gca011764245.GCA011764245v1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/tribolium_castaneum/pep/Tribolium_castaneum.Tcas5.2.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/trichinella_spiralis/pep/Trichinella_spiralis.Tspiralis1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/trichogramma_pretiosum_gca000599845v3/pep/Trichogramma_pretiosum_gca000599845v3.Tpre_2.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/trichoplax_adhaerens/pep/Trichoplax_adhaerens.ASM15027v1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/trichuris_muris/pep/Trichuris_muris.TMUE3.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/varroa_destructor_gca002443255/pep/Varroa_destructor_gca002443255.Vdes_3.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/metazoa/release-55/fasta/zootermopsis_nevadensis/pep/Zootermopsis_nevadensis.ZooNev1.0.pep.all.fa.gz -P fastas/
