wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/actinidia_chinensis/pep/Actinidia_chinensis.Red5_PS1_1.69.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/aegilops_tauschii/pep/Aegilops_tauschii.Aet_v4.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/amborella_trichopoda/pep/Amborella_trichopoda.AMTR1.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/ananas_comosus/pep/Ananas_comosus.F153.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/arabidopsis_halleri/pep/Arabidopsis_halleri.Ahal2.2.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/arabidopsis_lyrata/pep/Arabidopsis_lyrata.v.1.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/arabidopsis_thaliana/pep/Arabidopsis_thaliana.TAIR10.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/arabis_alpina/pep/Arabis_alpina.A_alpina_V4.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/asparagus_officinalis/pep/Asparagus_officinalis.Aspof.V1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/beta_vulgaris/pep/Beta_vulgaris.RefBeet-1.2.2.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/brachypodium_distachyon/pep/Brachypodium_distachyon.Brachypodium_distachyon_v3.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/brassica_juncea/pep/Brassica_juncea.ASM1870372v1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/brassica_napus/pep/Brassica_napus.AST_PRJEB5043_v1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/brassica_oleracea/pep/Brassica_oleracea.BOL.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/brassica_rapa/pep/Brassica_rapa.Brapa_1.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/brassica_rapa_ro18/pep/Brassica_rapa_ro18.SCU_BraROA_2.3.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/camelina_sativa/pep/Camelina_sativa.Cs.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/cannabis_sativa_female/pep/Cannabis_sativa_female.cs10.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/capsicum_annuum/pep/Capsicum_annuum.ASM51225v2.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/chara_braunii/pep/Chara_braunii.Cbr_1.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/chenopodium_quinoa/pep/Chenopodium_quinoa.ASM168347v1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/chlamydomonas_reinhardtii/pep/Chlamydomonas_reinhardtii.Chlamydomonas_reinhardtii_v5.5.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/chondrus_crispus/pep/Chondrus_crispus.ASM35022v2.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/citrullus_lanatus/pep/Citrullus_lanatus.Cla97_v1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/citrus_clementina/pep/Citrus_clementina.Citrus_clementina_v1.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/coffea_canephora/pep/Coffea_canephora.AUK_PRJEB4211_v1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/corchorus_capsularis/pep/Corchorus_capsularis.CCACVL1_1.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/corylus_avellana/pep/Corylus_avellana.CavTom2PMs-1.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/corymbia_citriodora/pep/Corymbia_citriodora.Ccitriodora_v2_1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/cucumis_melo/pep/Cucumis_melo.Melonv4.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/cucumis_sativus/pep/Cucumis_sativus.ASM407v2.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/cyanidioschyzon_merolae/pep/Cyanidioschyzon_merolae.ASM9120v1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/cynara_cardunculus/pep/Cynara_cardunculus.CcrdV1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/daucus_carota/pep/Daucus_carota.ASM162521v1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/digitaria_exilis/pep/Digitaria_exilis.Fonio_CM05836.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/dioscorea_rotundata/pep/Dioscorea_rotundata.TDr96_F1_v2_PseudoChromosome.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/echinochloa_crusgalli/pep/Echinochloa_crusgalli.ec_v3.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/eragrostis_curvula/pep/Eragrostis_curvula.CERZOS_E.curvula1.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/eragrostis_tef/pep/Eragrostis_tef.ASM97063v1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/eucalyptus_grandis/pep/Eucalyptus_grandis.Egrandis1_0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/eutrema_salsugineum/pep/Eutrema_salsugineum.Eutsalg1_0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/ficus_carica/pep/Ficus_carica.UNIPI_FiCari_1.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/galdieria_sulphuraria/pep/Galdieria_sulphuraria.ASM34128v1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/glycine_max/pep/Glycine_max.Glycine_max_v2.1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/gossypium_raimondii/pep/Gossypium_raimondii.Graimondii2_0_v6.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/helianthus_annuus/pep/Helianthus_annuus.HanXRQr2.0-SUNRISE.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/hordeum_vulgare/pep/Hordeum_vulgare.MorexV3_pseudomolecules_assembly.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/hordeum_vulgare_goldenpromise/pep/Hordeum_vulgare_goldenpromise.GPv1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/hordeum_vulgare_tritex/pep/Hordeum_vulgare_tritex.Morex_V2_scaf.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/ipomoea_triloba/pep/Ipomoea_triloba.ASM357664v1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/juglans_regia/pep/Juglans_regia.Walnut_2.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/kalanchoe_fedtschenkoi/pep/Kalanchoe_fedtschenkoi.K_fedtschenkoi_M2_v1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/lactuca_sativa/pep/Lactuca_sativa.Lsat_Salinas_v7.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/leersia_perrieri/pep/Leersia_perrieri.Lperr_V1.4.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/lolium_perenne/pep/Lolium_perenne.MPB_Lper_Kyuss_1697.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/lupinus_angustifolius/pep/Lupinus_angustifolius.LupAngTanjil_v1.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/malus_domestica_golden/pep/Malus_domestica_golden.ASM211411v1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/manihot_esculenta/pep/Manihot_esculenta.Manihot_esculenta_v6.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/marchantia_polymorpha/pep/Marchantia_polymorpha.Marchanta_polymorpha_v1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/medicago_truncatula/pep/Medicago_truncatula.MedtrA17_4.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/musa_acuminata/pep/Musa_acuminata.Musa_acuminata_v2.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/nicotiana_attenuata/pep/Nicotiana_attenuata.NIATTr2.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/nymphaea_colorata/pep/Nymphaea_colorata.ASM883128v1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/olea_europaea/pep/Olea_europaea.OLEA9.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/olea_europaea_sylvestris/pep/Olea_europaea_sylvestris.O_europaea_v1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/oryza_barthii/pep/Oryza_barthii.O.barthii_v1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/oryza_brachyantha/pep/Oryza_brachyantha.Oryza_brachyantha.v1.4b.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/oryza_glaberrima/pep/Oryza_glaberrima.Oryza_glaberrima_V1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/oryza_glumipatula/pep/Oryza_glumipatula.Oryza_glumaepatula_v1.5.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/oryza_indica/pep/Oryza_indica.ASM465v1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/oryza_longistaminata/pep/Oryza_longistaminata.O_longistaminata_v1.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/oryza_meridionalis/pep/Oryza_meridionalis.Oryza_meridionalis_v1.3.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/oryza_nivara/pep/Oryza_nivara.Oryza_nivara_v1.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/oryza_punctata/pep/Oryza_punctata.Oryza_punctata_v1.2.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/oryza_rufipogon/pep/Oryza_rufipogon.OR_W1943.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/oryza_sativa/pep/Oryza_sativa.IRGSP-1.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/ostreococcus_lucimarinus/pep/Ostreococcus_lucimarinus.ASM9206v1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/panicum_hallii/pep/Panicum_hallii.PhalliiHAL_v2.1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/panicum_hallii_fil2/pep/Panicum_hallii_fil2.PHallii_v3.1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/papaver_somniferum/pep/Papaver_somniferum.ASM357369v1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/phaseolus_vulgaris/pep/Phaseolus_vulgaris.PhaVulg1_0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/physcomitrium_patens/pep/Physcomitrium_patens.Phypa_V3.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/pistacia_vera/pep/Pistacia_vera.PisVer_v2.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/pisum_sativum/pep/Pisum_sativum.Pisum_sativum_v1a.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/populus_trichocarpa/pep/Populus_trichocarpa.Pop_tri_v3.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/prunus_avium/pep/Prunus_avium.PAV_r1.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/prunus_dulcis/pep/Prunus_dulcis.ALMONDv2.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/prunus_persica/pep/Prunus_persica.Prunus_persica_NCBIv2.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/quercus_lobata/pep/Quercus_lobata.ValleyOak3.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/quercus_suber/pep/Quercus_suber.CorkOak1.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/rosa_chinensis/pep/Rosa_chinensis.RchiOBHm-V2.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/saccharum_spontaneum/pep/Saccharum_spontaneum.Sspon.HiC_chr_asm.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/secale_cereale/pep/Secale_cereale.Rye_Lo7_2018_v1p1p1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/selaginella_moellendorffii/pep/Selaginella_moellendorffii.v1.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/sesamum_indicum/pep/Sesamum_indicum.S_indicum_v1.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/setaria_italica/pep/Setaria_italica.Setaria_italica_v2.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/setaria_viridis/pep/Setaria_viridis.Setaria_viridis_v2.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/solanum_lycopersicum/pep/Solanum_lycopersicum.SL3.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/solanum_tuberosum/pep/Solanum_tuberosum.SolTub_3.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/solanum_tuberosum_rh8903916/pep/Solanum_tuberosum_rh8903916.ASM1418947v1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/sorghum_bicolor/pep/Sorghum_bicolor.Sorghum_bicolor_NCBIv3.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/theobroma_cacao/pep/Theobroma_cacao.Theobroma_cacao_20110822.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/theobroma_cacao_criollo/pep/Theobroma_cacao_criollo.Criollo_cocoa_genome_V2.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/trifolium_pratense/pep/Trifolium_pratense.Trpr.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/triticum_aestivum/pep/Triticum_aestivum.IWGSC.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/triticum_aestivum_arinalrfor/pep/Triticum_aestivum_arinalrfor.PGSBv2.1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/triticum_aestivum_cadenza/pep/Triticum_aestivum_cadenza.EIv1.1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/triticum_aestivum_claire/pep/Triticum_aestivum_claire.EIv1.1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/triticum_aestivum_jagger/pep/Triticum_aestivum_jagger.PGSBv2.1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/triticum_aestivum_julius/pep/Triticum_aestivum_julius.PGSBv2.1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/triticum_aestivum_lancer/pep/Triticum_aestivum_lancer.PGSBv2.1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/triticum_aestivum_landmark/pep/Triticum_aestivum_landmark.PGSBv2.1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/triticum_aestivum_mace/pep/Triticum_aestivum_mace.PGSBv2.1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/triticum_aestivum_mattis/pep/Triticum_aestivum_mattis.PGSBv2.1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/triticum_aestivum_norin61/pep/Triticum_aestivum_norin61.PGSBv2.1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/triticum_aestivum_paragon/pep/Triticum_aestivum_paragon.EIv1.1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/triticum_aestivum_robigus/pep/Triticum_aestivum_robigus.EIv1.1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/triticum_aestivum_stanley/pep/Triticum_aestivum_stanley.PGSBv2.2.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/triticum_aestivum_weebil/pep/Triticum_aestivum_weebil.WeebilV1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/triticum_dicoccoides/pep/Triticum_dicoccoides.WEWSeq_v.1.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/triticum_spelta/pep/Triticum_spelta.PGSBv2.0.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/triticum_turgidum/pep/Triticum_turgidum.Svevo.v1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/triticum_urartu/pep/Triticum_urartu.IGDB.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/vigna_angularis/pep/Vigna_angularis.Vigan1.1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/vigna_radiata/pep/Vigna_radiata.Vradiata_ver6.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/vigna_unguiculata/pep/Vigna_unguiculata.ASM411807v1.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/vitis_vinifera/pep/Vitis_vinifera.PN40024.v4.pep.all.fa.gz -P fastas/
wget -c http://ftp.ensemblgenomes.org/pub/plants/release-55/fasta/zea_mays/pep/Zea_mays.Zm-B73-REFERENCE-NAM-5.0.pep.all.fa.gz -P fastas/
